"""Generate notebooks/analysis_template.ipynb programmatically.

Usage
-----
    python scripts/gen_analysis_notebook.py           # write/overwrite notebooks/analysis_template.ipynb
    python scripts/gen_analysis_notebook.py --check   # exit 1 if committed file differs from generated

The notebook has four RQ sections:
  - RQ1: Pareto frontier, topology x task heatmap, phase timeline
  - RQ2: All 7 G11 derived-metrics + 5 plot functions
  - RQ3: Placeholder (out-of-scope for M13)
  - RQ4: Cognitive-load boxplot, oracle vs router
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import nbformat
from nbformat import v4 as nbv4

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent
_OUTPUT_PATH = _REPO_ROOT / "notebooks" / "analysis_template.ipynb"

# ---------------------------------------------------------------------------
# Cell building helpers
# ---------------------------------------------------------------------------


def _md(text: str) -> nbformat.NotebookNode:
    """Create a markdown cell."""
    return nbv4.new_markdown_cell(text.strip())  # type: ignore[no-untyped-call,no-any-return]


def _code(text: str) -> nbformat.NotebookNode:
    """Create a code cell with stripped source."""
    return nbv4.new_code_cell(text.strip())  # type: ignore[no-untyped-call,no-any-return]


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------


def _setup_cells() -> list[nbformat.NotebookNode]:
    """Preamble: imports and experiment setup."""
    return [
        _md(
            "# ATM Analysis — Template Notebook\n\n"
            "Generated by `scripts/gen_analysis_notebook.py`.\n\n"
            "Fill in `EXPERIMENT_ID` and `ARTIFACTS_BASE` before running."
        ),
        _code(
            "# Standard imports\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "\n"
            "# ATM analysis API\n"
            "from atm.analysis import (\n"
            "    load_experiment,\n"
            "    load_runs,\n"
            "    load_topology_transitions,\n"
            "    load_phases,\n"
            "    load_human_interactions,\n"
            "    load_llm_calls_for_experiment,\n"
            "    load_oracle_table,\n"
            "    compute_guard_override_rate,\n"
            "    compute_router_cost_share,\n"
            "    compute_time_per_topology,\n"
            "    compute_oracle_gap_loo,\n"
            "    compute_oracle_gap_manual,\n"
            "    compute_hurt_rate,\n"
            "    compute_topology_switch_counts,\n"
            "    plot_pareto,\n"
            "    plot_topology_task_heatmap,\n"
            "    plot_phase_timeline,\n"
            "    plot_transition_timeline_quality,\n"
            "    plot_guard_override_rate,\n"
            "    plot_router_cost_share,\n"
            "    plot_time_per_topology,\n"
            "    plot_oracle_gap_loo,\n"
            "    plot_cognitive_load_boxplot,\n"
            "    plot_oracle_vs_router,\n"
            ")"
        ),
        _code(
            "# --- Configure experiment ---\n"
            "EXPERIMENT_ID = 'YOUR_EXPERIMENT_ID_HERE'\n"
            "PG_DSN = 'postgresql+asyncpg://user:pass@localhost/atm'\n"
            "ARTIFACTS_BASE = 'experiments'  # base directory for parquet artefacts"
        ),
        _code(
            "# Load experiment metadata and all runs\n"
            "import asyncio\n"
            "\n"
            "experiment = asyncio.run(load_experiment(EXPERIMENT_ID, dsn=PG_DSN))\n"
            "runs_df = asyncio.run(load_runs(EXPERIMENT_ID, dsn=PG_DSN))\n"
            "print(f'Loaded {len(runs_df)} runs')\n"
            "runs_df.head()"
        ),
        _code(
            "# Load transition, phase, human-interaction, and LLM-call data\n"
            "transitions_df = asyncio.run(\n"
            "    load_topology_transitions(EXPERIMENT_ID, dsn=PG_DSN)\n"
            ")\n"
            "phases_df = asyncio.run(load_phases(EXPERIMENT_ID, dsn=PG_DSN))\n"
            "human_df = asyncio.run(load_human_interactions(EXPERIMENT_ID, dsn=PG_DSN))\n"
            "llm_df = load_llm_calls_for_experiment(\n"
            "    EXPERIMENT_ID, artifacts_base=ARTIFACTS_BASE\n"
            ")"
        ),
        _code("oracle = load_oracle_table()"),
    ]


def _rq1_cells() -> list[nbformat.NotebookNode]:
    """RQ1: Pareto frontier, heatmap, phase timeline."""
    return [
        _md(
            "## RQ1 — Does the adaptive topology Pareto-dominate static topologies?\n\n"
            "Plots: (a) quality vs cost Pareto scatter, "
            "(b) topology x task heatmap, (c) phase timeline."
        ),
        _code(
            "# RQ1a: Pareto frontier — quality vs cost\n"
            "fig_pareto = plot_pareto(runs_df)\n"
            "plt.show()"
        ),
        _code(
            "# RQ1b: Topology x task-type heatmap\n"
            "fig_heatmap = plot_topology_task_heatmap(runs_df)\n"
            "plt.show()"
        ),
        _code(
            "# RQ1c: Phase timeline (Gantt)\n"
            "fig_timeline = plot_phase_timeline(phases_df)\n"
            "plt.show()"
        ),
    ]


def _rq2_cells() -> list[nbformat.NotebookNode]:
    """RQ2: G11 derived metrics + 5 plot functions."""
    return [
        _md(
            "## RQ2 — Safety: do adaptive guards reduce quality regression?\n\n"
            "Derived G11 metrics (experiment_plan.md §4) and their visualisations."
        ),
        _code(
            "# RQ2 — Derived metrics\n"
            "\n"
            "# 1. Hurt rate — fraction of tasks where Adaptive < best static\n"
            "# Compute best static quality per task_id (exclude 'adaptive' topology)\n"
            "static_runs = runs_df[runs_df['topology'] != 'adaptive']\n"
            "best_static_df = (\n"
            "    static_runs.groupby('task_id')['quality_score']\n"
            "    .max()\n"
            "    .reset_index()\n"
            "    .rename(columns={'quality_score': 'best_static_quality'})\n"
            ")\n"
            "hurt_rate = compute_hurt_rate(runs_df, best_static_df)\n"
            "print(f'Hurt rate: {hurt_rate:.3f}')"
        ),
        _code(
            "# 2. Oracle gap (manual) — quality gap vs manual oracle per task_id\n"
            "oracle_gap_manual = compute_oracle_gap_manual(runs_df, oracle)\n"
            "print(oracle_gap_manual.describe())"
        ),
        _code(
            "# 3. Oracle gap (LOO) — quality gap vs leave-one-out oracle per task_id\n"
            "oracle_gap_loo = compute_oracle_gap_loo(runs_df, oracle)\n"
            "print(oracle_gap_loo.describe())"
        ),
        _code(
            "# 4. Topology switch counts per run\n"
            "switch_counts = compute_topology_switch_counts(transitions_df)\n"
            "print(switch_counts.describe())"
        ),
        _code(
            "# 5. Guard override rate — fraction of router decisions that were guard overrides\n"
            "guard_override_rate = compute_guard_override_rate(transitions_df)\n"
            "print(f'Guard override rate: {guard_override_rate:.3f}')"
        ),
        _code(
            "# 6. Router cost share — router cost as fraction of total run cost\n"
            "router_cost_share = compute_router_cost_share(transitions_df, runs_df)\n"
            "print(f'Router cost share: {router_cost_share:.4f}')"
        ),
        _code(
            "# 7. Time per topology — active wall-time fraction per topology\n"
            "time_per_topo = compute_time_per_topology(phases_df)\n"
            "print(time_per_topo)"
        ),
        _code(
            "# RQ2 plots\n"
            "\n"
            "# G11a: Transition timeline + quality overlay\n"
            "fig_transitions = plot_transition_timeline_quality(transitions_df, runs_df)\n"
            "plt.show()"
        ),
        _code(
            "# G11b: Guard override rate per topology\n"
            "fig_guard = plot_guard_override_rate(transitions_df)\n"
            "plt.show()"
        ),
        _code(
            "# G11c: Router cost share per run\n"
            "fig_router_cost = plot_router_cost_share(transitions_df, runs_df)\n"
            "plt.show()"
        ),
        _code(
            "# G11d: Time per topology\n"
            "fig_time_topo = plot_time_per_topology(phases_df)\n"
            "plt.show()"
        ),
        _code(
            "# G11e: Oracle gap (LOO) distribution\n"
            "fig_oracle_gap = plot_oracle_gap_loo(oracle_gap_loo)\n"
            "plt.show()"
        ),
    ]


def _rq3_cells() -> list[nbformat.NotebookNode]:
    """RQ3: Placeholder — out of scope for M13."""
    return [
        _md(
            "## RQ3 — Latency and throughput under adaptive routing\n\n"
            "> **Placeholder** — analysis for RQ3 is out of scope for M13 "
            "and will be implemented in M14+.\n\n"
            "Expected content: latency distribution per topology, "
            "throughput (tasks/min) comparison, p50/p95 percentiles."
        ),
        _code(
            "# RQ3 placeholder\n"
            "# TODO (M14+): implement latency/throughput analysis\n"
            "print('RQ3 analysis not yet implemented.')"
        ),
    ]


def _rq4_cells() -> list[nbformat.NotebookNode]:
    """RQ4: Cognitive load boxplot and oracle vs router."""
    return [
        _md(
            "## RQ4 — Human-in-the-loop: does HITL reduce cognitive load?\n\n"
            "Plots: (a) cognitive load boxplot (raw TLX + proxy), "
            "(b) oracle vs router quality comparison."
        ),
        _code(
            "# RQ4a: Cognitive load boxplot\n"
            "# Requires runs_df (with cognitive_load_proxy) + human_df (with raw_tlx_score)\n"
            "fig_cog = plot_cognitive_load_boxplot(runs_df, human_df)\n"
            "plt.show()"
        ),
        _code(
            "# RQ4b: Oracle vs router quality\n"
            "fig_oracle = plot_oracle_vs_router(runs_df, oracle)\n"
            "plt.show()"
        ),
    ]


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------


def generate_notebook() -> nbformat.NotebookNode:
    """Build and return a new NotebookNode for the ATM analysis template.

    The notebook is structured as:
      - Preamble / setup
      - RQ1 section
      - RQ2 section (all 7 metric symbols + 5 plot functions)
      - RQ3 section (placeholder)
      - RQ4 section

    Returns:
        A fully populated nbformat 4 NotebookNode that passes nbformat.validate().
    """
    cells: list[nbformat.NotebookNode] = []
    cells.extend(_setup_cells())
    cells.extend(_rq1_cells())
    cells.extend(_rq2_cells())
    cells.extend(_rq3_cells())
    cells.extend(_rq4_cells())

    nb = nbv4.new_notebook(cells=cells)  # type: ignore[no-untyped-call]

    # Set kernel metadata so nbformat.validate() is satisfied
    nb.metadata["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    nb.metadata["language_info"] = {
        "name": "python",
        "version": "3.11.0",
    }

    return nb  # type: ignore[no-any-return]


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def _write_notebook(nb: nbformat.NotebookNode, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        nbformat.write(nb, fh)  # type: ignore[no-untyped-call]


def _cell_sources(nb: nbformat.NotebookNode) -> list[str]:
    return [cell["source"] for cell in nb.cells]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate notebooks/analysis_template.ipynb")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the committed notebook differs from the generated one.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_OUTPUT_PATH,
        help="Output path (default: notebooks/analysis_template.ipynb)",
    )
    args = parser.parse_args(argv)

    nb = generate_notebook()
    nbformat.validate(nb)

    if args.check:
        committed_path: Path = args.output
        if not committed_path.exists():
            print(
                f"ERROR: committed notebook not found at {committed_path}",
                file=sys.stderr,
            )
            return 1
        committed_nb = nbformat.read(str(committed_path), as_version=4)  # type: ignore[no-untyped-call]
        if _cell_sources(nb) != _cell_sources(committed_nb):
            print(
                "ERROR: committed notebook differs from generator output.\n"
                f"Re-run `python scripts/gen_analysis_notebook.py` to update {committed_path}",
                file=sys.stderr,
            )
            return 1
        print("OK: committed notebook matches generator output.")
        return 0

    _write_notebook(nb, args.output)
    print(f"Written: {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
